version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment: ## only when starting the db for the 1st time
      POSTGRES_PASSWORD: "secret123!"
      POSTGRES_USER: servers
      POSTGRES_DB: servers
    volumes:
      - 'psqldata:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
  adminer:
    command: php -S 0.0.0.0:8080 -t /var/www/html
    depends_on:
      - postgres
    image: 'adminer:4.7.7-standalone'
    ports:
      - '8080:8080'
    environment: ## only when starting the db for the 1st time
      POSTGRES_PASSWORD: secret123!
      POSTGRES_USER: servers
      POSTGRES_DB: servers
volumes:
   psqldata:
