apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: djinn506/racksbackend:test
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: "isabelle.db.elephantsql.com"
        - name: DB_USER
          value: "fnuofqyg"
        - name: DB_NAME
          value: "fnuofqyg"
        - name: DB_PASSWORD
          value: "e7_tfGw5noqS8o1QkyrV89Th0EfB7ohV"
